# syntax = docker/dockerfile:1

FROM node:20-alpine AS base

ENV NODE_ENV=test

WORKDIR /src

# Install dependencies
FROM base as deps

COPY --link package.json package-lock.json ./
RUN npm ci --prefer-offline --no-audit

# Setup for tests
FROM base

COPY --from=deps /src/node_modules /src/node_modules
COPY --link . .

# Generate Nuxt types and prepare environment
RUN npm run postinstall || true

CMD [ "npm", "run", "test" ]