# syntax = docker/dockerfile:1

FROM node:20-alpine AS base

ENV NODE_ENV=development

WORKDIR /src

# Install dependencies
FROM base as build

COPY --link package.json package-lock.json ./
RUN npm ci --prefer-offline --no-audit

# Run stage
FROM base

# Copy node_modules from build
COPY --from=build /src/node_modules /src/node_modules

# Run as root - we'll handle permissions via docker-compose user directive
CMD [ "npm", "run", "dev" ]