services:
  my-app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - .:/src
      - /src/node_modules
      - /src/.nuxt
    working_dir: /src
    environment:
      - NODE_ENV=development
    command: npm run dev